site_name: Conatus Notes
site_url: https://conatusnotes.github.io

docs_dir: docs

theme:
  name: material
  font: false

  palette:
    scheme: default

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

extra_css:
  - stylesheets/site.css

