site_name: Conatus Notes

theme:
  name: material
  font: false

  palette:
    scheme: default

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

not_in_nav: |
  /index.md

extra_css:
  - stylesheets/site.css
